### ISSUE TITLE
Invalid Chirila links

### ISSUE THREAD

**Issue by xrotwang** [clld/amsd-data#29]
It seems that links to Chirila have not been checked for validity. E.g. http://chirila.yale.edu/languages/Gudjal gets HTTP 500. Possibly that's a problem of the Chirila database, but maybe we want to make sure links work before showing them to users.

**Comment by Bibiko** [comment]
It seems that the Chirila site is under construction - the language map doesn't work right now either - I tested them manually some while ago and they worked - I'll try to test them while initializing the DB.

**Comment by perezkelly** [comment]
Yes, the Chirila map is very much incomplete.

I have access to a much bigger Chirila dataset that is not yet published
online and may never be. (It exists as a .kmz file from Claire Bowern's
website and she has allowed me to use it.) I just wanted to include it in
the AMSD because Claire's language names and coordinates are very reliable
and up to date.

But, as far as I'm concerned the Chirila language names don't need to
actually link through to a specific entry on the Chirila map. I'm quite
happy if all of them just link straight to http://chirila.yale.edu/languages

**Comment by Bibiko** [comment]
Closed with https://github.com/clld/amsd/pull/27
